/* ============================================================
   ARTICLES (extra batch) — Dalton Lab publications
   Added to the "Artigos" tab. Appended to window.DL_ARTICLES,
   consumed by insights.js. PT content (EN mirrors PT for now).
   ============================================================ */
(function () {
  const t = (pt, en) => ({ pt, en });
  const one = (s) => ({ pt: s, en: s });
  const h = (s) => ({ t: "h", pt: s, en: s });
  const p = (s) => ({ t: "p", pt: s, en: s });
  const q = (s) => ({ t: "q", pt: s, en: s });
  const DATE = t("5 jun 2026", "Jun 5, 2026");
  const PAPER = "assets/papers/dalton-lab-framework-agentico.pdf";

  const NEW = [
    /* ====================== ARTIGO 1 ====================== */
    {
      id: "o-que-e-organizacao-agentica",
      kind: "article",
      cat: one("Tese"),
      date: DATE,
      read: 7,
      art: "art-1",
      pdf: true,
      pdfUrl: PAPER,
      title: one("O que é Organização Agêntica e por que vai substituir o modelo industrial de empresas"),
      dek: one("Hierarquias rígidas estão se tornando obsoletas. O que as substitui tem nome — e uma definição precisa."),
      body: [
        p("89% das empresas no mundo ainda operam com o mesmo modelo organizacional das décadas anteriores: hierarquias rígidas, fluxos de decisão lentos, profissionais seniores consumidos por tarefas repetitivas. É o modelo industrial. Funciona. Mas está se tornando obsoleto em velocidade que a maioria das lideranças ainda não dimensionou."),
        p("O que está substituindo esse modelo tem um nome: organização agêntica."),
        h("O que é uma organização agêntica"),
        p("Uma organização agêntica é uma empresa onde agentes de IA operam como membros permanentes da equipe, com responsabilidades definidas, métricas de performance e capacidade de executar tarefas de ponta a ponta, sob supervisão e governança humana."),
        p("Cada palavra dessa definição importa."),
        p("“Membros permanentes” significa que não são pilotos, projetos ou testes. São parte da estrutura operacional, com escopo definido, como qualquer contratação."),
        p("“Responsabilidades definidas” significa que cada agente tem um limite claro do que faz e do que não faz: pode qualificar um lead e agendar uma reunião, mas não pode fechar um contrato."),
        p("“Métricas de performance” significa que agentes são medidos por resultado, exatamente como qualquer profissional."),
        p("E “supervisão e governança humana” significa que humanos definem as regras, os limites e os pontos de escalação. Agentes executam dentro desses parâmetros."),
        q("A autonomia de um agente não é absoluta. É delegada, limitada e controlada."),
        h("O que uma organização agêntica não é"),
        p("Três equívocos dominam a conversa sobre IA nas empresas, e os três levam a decisões erradas."),
        p("O primeiro: “organização agêntica é ter ChatGPT aberto nos computadores dos funcionários.” Não é. Uso individual de IA é útil, mas limitado. Não muda processos. Não muda resultados organizacionais."),
        p("Uma empresa onde cada pessoa usa IA por conta própria, sem integração, sem governança e sem métricas não é uma organização agêntica. É uma empresa com funcionários individualmente mais produtivos e igualmente ineficiente como sistema."),
        p("O segundo: “organização agêntica é substituir pessoas por bots.” Não é. O objetivo é amplificação da capacidade humana. IA assume o trabalho operacional e repetitivo para que humanos possam focar no que só humanos fazem: estratégia, criatividade e relacionamento."),
        p("Empresas que tratam a transição agêntica como programa de redução de headcount chegam a resultados piores do que as que não fazem nada. Os dados são inequívocos: o ato de cortar pessoas, isoladamente, não gera retorno sobre o investimento em IA. (Gartner, 2026)"),
        p("O terceiro: “organização agêntica é um projeto de TI.” Não é. É uma mudança de modelo operacional. Exige redesenho de processos, preparação de pessoas e, apenas então, implementação de ferramentas. Empresas que invertem essa sequência automatizam o caos."),
        q("Um agente executando um processo ruim não resolve o processo. Acelera os erros em escala maior."),
        h("A diferença estrutural"),
        p("O modelo industrial foi desenhado para um mundo onde informação era escassa e centralizar decisão em quem tinha mais contexto fazia sentido. Funcionou por décadas porque era a melhor resposta disponível para o problema de coordenar trabalho em escala."),
        p("Esse mundo não existe mais. Informação é abundante. O que é escasso é velocidade."),
        p("No modelo industrial, uma decisão operacional simples escala três níveis antes de acontecer. Um cliente reclama. O atendente consulta o supervisor. O supervisor consulta o gerente. O gerente aprova 48 horas depois. O cliente já foi embora."),
        p("Numa organização agêntica, agentes tomam decisões operacionais dentro de parâmetros definidos, instantaneamente. O humano define as regras. O agente executa. A exceção escala. A rotina flui."),
        p("A diferença não é de grau. É de estrutura. Uma organização agêntica não é uma empresa convencional com menos pessoas e mais automação. É uma forma estruturalmente diferente de distribuir responsabilidades, de definir quem faz o quê e de medir o que conta como resultado."),
        p("Organogramas hierárquicos descrevem quem reporta a quem. Em organizações agênticas, o que importa é quem é responsável por qual entrega, independentemente de posição hierárquica."),
        h("Por que vai substituir o modelo industrial"),
        p("Menos de 1% das empresas globais opera hoje como organização agêntica. Mas esse número está mudando com velocidade que poucos líderes anteciparam."),
        p("Empresas no estágio mais avançado de maturidade agêntica operam com 70% a 80% menos custo por transação do que as que ainda operam no modelo industrial. (McKinsey)"),
        p("Isso não é uma desvantagem competitiva. É uma impossibilidade estrutural. Não se compete no mesmo mercado com uma estrutura de custos três a quatro vezes maior indefinidamente."),
        p("O modelo industrial não vai desaparecer amanhã. Mas a janela de vantagem competitiva para quem se move primeiro está aberta agora. 76% dos executivos globais já veem agentes de IA como colegas de trabalho, não como ferramentas. Essa mudança de mentalidade não está acontecendo nos departamentos de TI. Está acontecendo nos boards. (MIT/BCG)"),
        h("O que líderes que estão se movendo fazem diferente"),
        p("A diferença entre empresas que estão construindo vantagem agêntica e as que estão ficando para trás não é tecnológica. É de sequência."),
        p("Empresas que avançam começam pelo diagnóstico, não pela ferramenta. Mapeiam onde estão, quais processos têm maior potencial de transformação e qual é o próximo passo concreto. Depois agem rápido, no processo que mais dói, com governança desde o dia zero."),
        p("Empresas que ficam para trás começam pela tecnologia. Contratam uma plataforma. Testam um chatbot. Implementam um agente. E descobrem, seis meses depois, que têm um processo mal desenhado operado por pessoas que não entendem o que mudou."),
        p("A sequência correta é inegociável: processos primeiro, pessoas em segundo, ferramentas de IA em terceiro. Invertê-la não acelera a transformação. Garante o fracasso."),
        h("O ponto de partida"),
        p("Organização agêntica não é um destino que se alcança de uma vez. É uma jornada com estágios distintos, e cada estágio tem características operacionais concretas que indicam onde a empresa está."),
        p("Acompanhamos empresas nessa transição, do primeiro agente em produção até a operação agêntica em escala. O que separa as que avançam das que travam não é orçamento nem tecnologia. É clareza sobre onde estão e honestidade sobre o que ainda falta."),
        p("A pergunta relevante para qualquer líder não é “quando vamos nos tornar uma organização agêntica?”. É “em que estágio estamos hoje, qual processo transformaríamos agora, e o que nos impede de começar?”. A resposta revela mais sobre a prontidão da organização do que qualquer declaração de intenção."),
      ],
    },

    /* ====================== ARTIGO 2 ====================== */
    {
      id: "o-que-e-transformacao-agentica",
      kind: "article",
      cat: one("Conceito"),
      date: DATE,
      read: 6,
      art: "art-2",
      pdf: true,
      pdfUrl: PAPER,
      title: one("O que é Transformação Agêntica, o novo patamar além da transformação digital"),
      dek: one("Não é tecnologia mais sofisticada. É partir de uma pergunta diferente."),
      body: [
        p("88% das empresas globais usam IA. Apenas 39% conseguem atribuir impacto real nos resultados do negócio. (McKinsey, 2025)"),
        p("A maioria das iniciativas de transformação digital prometeu eficiência e entregou projetos. A maioria das iniciativas de IA prometeu produtividade e entregou ferramentas."),
        p("Transformação agêntica é diferente. Não porque usa tecnologia mais sofisticada. Porque parte de uma pergunta diferente."),
        h("Por que a transformação digital ficou pela metade"),
        p("A transformação digital digitalizou processos. Substituiu papel por sistema. Planilha por ERP. Reunião presencial por videochamada. Foi necessário. Mas não foi suficiente."),
        p("O problema central da transformação digital é que ela tornou os processos existentes mais rápidos, sem questionar se esses processos deveriam existir na forma como existiam."),
        p("Uma empresa que leva 48 horas para aprovar um reembolso não precisa de um sistema digital para aprovar em 47 horas. Precisa questionar por que um reembolso abaixo de determinado valor exige aprovação humana em primeiro lugar."),
        p("Esse questionamento não estava no escopo da transformação digital. Está no centro da transformação agêntica."),
        h("O que é transformação agêntica"),
        p("Transformação agêntica é a mudança de modelo operacional que permite a uma empresa integrar agentes de IA como membros permanentes da equipe, com responsabilidades definidas, métricas de performance e supervisão humana."),
        p("Não é uma iniciativa de TI. Não é um projeto de automação. É um redesenho de como o trabalho é distribuído entre humanos e agentes."),
        p("No Dalton Lab, definimos transformação agêntica como uma abordagem end-to-end que atua em três dimensões, nessa ordem: processos, pessoas e ferramentas de IA. A sequência não é negociável."),
        p("A maioria das empresas inverte essa ordem. Começa pela ferramenta porque é o que parece mais concreto. E fracassa porque uma ferramenta aplicada a um processo ruim, operada por pessoas que não entendem o que mudou, não transforma nada. Acelera o que já estava errado."),
        h("A diferença que define o resultado"),
        p("O que distingue a transformação agêntica da transformação digital não é a tecnologia envolvida. É o nível de mudança que ela exige."),
        q("A transformação digital mudou os sistemas que as pessoas usam. A transformação agêntica muda quem faz o quê."),
        p("Parte do trabalho que hoje é feito por humanos passa a ser feito por agentes. Parte do trabalho que consome o tempo de profissionais seniores é liberada para que esses profissionais façam o que só humanos podem fazer. A estrutura da empresa muda. Os papéis mudam. A governança muda."),
        p("Empresas que tratam transformação agêntica como mais uma camada de automação por cima da transformação digital chegam ao mesmo resultado de sempre: projetos que não escalam, ferramentas subutilizadas e lideranças frustradas com o retorno que não vem."),
        p("Os dados confirmam esse padrão. 95% das empresas que adotam IA extensivamente não conseguem retorno mensurável. Apenas 5% chegam à produção com resultados reais. (MIT, 2025) A diferença entre esses dois grupos não está no tamanho do investimento ou na sofisticação da tecnologia. Está na abordagem."),
        h("O que as empresas bem-sucedidas fazem diferente"),
        p("Empresas que conseguem resultado real com transformação agêntica compartilham três características."),
        p("1 — Começam com diagnóstico, não com compra. Antes de contratar qualquer plataforma ou implementar qualquer agente, mapeiam processos, identificam gargalos e entendem onde a transformação teria maior impacto nos próximos 90 dias. Essa etapa elimina o erro mais comum: automatizar o que não precisava existir."),
        p("2 — Redesenham o processo antes de colocar o agente. IA sobre processo antigo não melhora o processo. Amplifica seus problemas em escala e velocidade. O redesenho vem primeiro. O agente vem depois."),
        p("3 — Investem em pessoas antes de investir em ferramentas. O time precisa entender o que muda, por que muda e o que se espera de cada um. Resistência à transformação agêntica raramente é resistência à mudança. É, quase sempre, falta de preparo. E a responsabilidade é da liderança, não do time."),
        h("O novo patamar"),
        p("Transformação digital foi sobre velocidade. Transformação agêntica é sobre estrutura."),
        p("Uma empresa que completou a transformação digital opera processos manuais de forma digital. Uma empresa que avança na transformação agêntica opera com uma arquitetura diferente: humanos definem estratégia, supervisionam e tomam decisões complexas, enquanto agentes executam o trabalho operacional com consistência, velocidade e escala que nenhum time humano consegue replicar."),
        p("Essa não é uma diferença de grau. É uma diferença de modelo."),
        p("A pergunta que cada líder precisa responder não é “já fizemos a transformação digital?”. É “o que ainda está sendo feito por humanos que poderia ser operado por agentes, liberando nosso time para o trabalho que só humanos fazem?”. A resposta a essa pergunta define onde começa a transformação agêntica."),
      ],
    },

    /* ====================== ARTIGO 3 ====================== */
    {
      id: "o-que-e-agente-de-ia",
      kind: "article",
      cat: one("Conceito"),
      date: DATE,
      read: 6,
      art: "art-3",
      pdf: true,
      pdfUrl: PAPER,
      title: one("O que é um agente de IA e a diferença entre automação, copiloto e agente autônomo"),
      dek: one("Os três termos não são equivalentes. Confundi-los é o primeiro erro caro."),
      body: [
        p("O mercado usa os termos “automação”, “copiloto” e “agente de IA” como se fossem equivalentes. Não são. E confundi-los é a primeira decisão errada que a maioria das empresas toma quando começa a trabalhar com IA."),
        p("A distinção não é semântica. Cada modelo implica uma arquitetura diferente, um nível de governança diferente e um impacto organizacional diferente. Entender onde cada um se aplica é o que separa uma estratégia de IA que gera resultado de uma coleção de ferramentas que se acumulam sem escalar."),
        h("Automação tradicional: regras fixas, zero contexto"),
        p("Automação tradicional, como RPA e scripts de processo, funciona por regras fixas. O sistema executa o que foi programado para executar, na sequência que foi definida, sem capacidade de interpretar variações."),
        p("Se o dado chega no formato esperado, o processo funciona. Se chega com um campo a mais ou com a estrutura diferente, o processo quebra. Automação tradicional é eficiente dentro de condições controladas. Fora dessas condições, é frágil."),
        p("Isso não significa que automação tradicional não tem valor. Tem, em processos altamente padronizados com baixa variação. O problema é quando empresas chamam automação de IA agêntica e esperam o comportamento de um agente."),
        h("Copiloto: o assistente que amplifica, mas não age"),
        p("O modelo copiloto é o que a maioria das pessoas experimenta quando usa ChatGPT, Claude ou Gemini no trabalho. A IA processa informação, gera conteúdo, responde perguntas e sugere ações. Mas quem decide e quem executa é o humano."),
        p("O copiloto amplifica a produtividade individual. Um profissional com um bom copiloto produz mais, em menos tempo, com menos esforço cognitivo. Isso tem valor real. Mas não muda a estrutura da empresa. Não redesenha processos. Não redistribui trabalho entre humanos e sistemas."),
        q("Uma organização onde todos usam copilotos individualmente é uma organização com profissionais mais produtivos. Não é uma organização agêntica."),
        h("Agente autônomo: contexto, decisão e execução"),
        p("Um agente de IA é diferente dos dois modelos anteriores em três dimensões fundamentais."),
        p("Primeiro, agentes interpretam contexto. Não seguem regras fixas. Leem situações, processam variações e tomam decisões dentro de parâmetros definidos. Se a informação chega com formato inesperado, o agente interpreta o conteúdo e age de acordo com o objetivo, não com a regra."),
        p("Segundo, agentes tomam decisões operacionais. Dentro de um escopo definido, o agente decide o que fazer sem intervenção humana em cada etapa. Ele qualifica o lead, agenda a reunião, atualiza o CRM e notifica o vendedor. Não espera aprovação para cada ação."),
        p("Terceiro, agentes executam de ponta a ponta. Não geram uma sugestão para o humano implementar. Executam o processo completo, com integração aos sistemas da empresa, e escalam para o humano apenas quando a situação sai dos parâmetros definidos."),
        h("Os três elementos de um agente organizacional"),
        p("Todo agente que opera dentro de uma organização agêntica tem três características que precisam estar presentes antes de entrar em produção."),
        p("O primeiro é autonomia definida: o agente tem um escopo claro do que pode e não pode fazer, estabelecido antes da implementação. Os limites são parte do design, não uma restrição adicionada depois."),
        p("O segundo é integração sistêmica: o agente está conectado aos sistemas da empresa. Opera dentro do fluxo real de trabalho, não em paralelo a ele. Um agente que não está conectado ao CRM, ao ERP ou às ferramentas de comunicação da empresa não é um agente organizacional. É um chatbot isolado."),
        p("O terceiro é accountability mensurável: o agente tem métricas. Tempo de resposta, taxa de acerto, volume processado, número de escalações. Se não está performando, é ajustado ou substituído. O mesmo padrão que se aplica a qualquer profissional."),
        h("Por que a distinção define sua estratégia"),
        p("A confusão entre esses três modelos cria dois problemas opostos."),
        p("O primeiro é superestimar a automação tradicional. Empresas que chamam RPA de IA agêntica criam expectativas que o sistema não consegue entregar e chegam à conclusão errada de que “IA não funciona para o nosso caso”."),
        q("Implementar um agente sem definir seu escopo, sem integrá-lo aos sistemas e sem estabelecer métricas é lançar um profissional novo sem job description, sem acesso aos sistemas e sem avaliação de performance."),
        p("O segundo é subestimar o que um agente real exige. O resultado é previsível."),
        p("A pergunta correta não é “qual ferramenta de IA vamos usar?”. É “qual processo queremos transformar, qual nível de autonomia faz sentido para esse processo e qual arquitetura suporta isso com governança adequada?”. A resposta a essa pergunta define se a empresa vai avançar ou vai colecionar ferramentas que não escalam."),
      ],
    },

    /* ====================== ARTIGO 4 ====================== */
    {
      id: "ai-last-ordem-importa",
      kind: "article",
      cat: one("Método"),
      date: DATE,
      read: 6,
      art: "art-4",
      pdf: true,
      pdfUrl: PAPER,
      title: one("AI Last, not AI First e por que a ordem importa mais do que a tecnologia"),
      dek: one("O gap da IA não é de tecnologia. É de sequência — e o ClickUp mostrou por quê."),
      body: [
        p("88% das empresas globais usam IA. Apenas 39% conseguem atribuir impacto real no resultado do negócio. (McKinsey, 2025) O gap não é de tecnologia. É de sequência."),
        p("A maioria das empresas começa pela ferramenta porque parece o caminho mais direto. Compra-se a plataforma, treina-se o time, espera-se o resultado. Quando o resultado não vem, a conclusão natural é que a ferramenta não era boa, que o modelo precisava de ajuste ou que a empresa ainda não estava pronta."),
        p("Quase sempre, o diagnóstico está errado. O problema não é a ferramenta. É a ordem."),
        h("O que o ClickUp revelou"),
        p("Em 2026, o ClickUp anunciou uma reestruturação profunda: demissão de 22% do quadro e reorganização em torno de agentes de IA, com razão de 2,3 agentes por humano. O que tornou esse anúncio analiticamente relevante não foi o corte. Foi a explicação."),
        p("Zeb Evans, CEO da empresa, foi explícito sobre o ponto de partida da reestruturação. O ClickUp não começou pela IA. Começou por uma pergunta anterior: quais sistemas precisam ser reconstruídos para que a IA faça sentido neles? A IA entrou depois que os processos foram repensados. Não antes."),
        p("Essa sequência tem um nome. No Dalton Lab, usamos o mesmo princípio que Evans descreveu: AI Last, not AI First."),
        h("O que acontece quando a IA vem primeiro"),
        q("IA sobre processo antigo não resolve o processo. Amplifica seus erros em velocidade maior e em escala maior."),
        p("Uma equipe de atendimento que demora 48 horas para resolver uma reclamação porque o processo exige três aprovações não fica mais rápida com um agente de IA inserido no meio do fluxo. O agente vai executar mais rápido a parte que opera, mas o gargalo continua nas aprovações. E agora há um agente produzindo volume maior na entrada de um processo que ainda não processa em velocidade adequada."),
        p("Organizações que automatizam o que está quebrado produzem mais do que estava errado, de forma mais rápida."),
        h("A pergunta que vem antes"),
        p("A primeira pergunta da transição agêntica não é “onde colocamos IA?”. É “qual processo nós pararíamos de fazer se pudéssemos?”."),
        p("Essa pergunta revela dois tipos de processo. O primeiro são processos que existem porque sempre existiram, sem que ninguém tenha questionado sua necessidade. Automatizar esses processos é um erro. O certo é eliminá-los."),
        p("O segundo são processos que precisam existir mas que estão mal desenhados para o contexto atual. Esses são os candidatos corretos para a transformação agêntica: primeiro redesenha-se o processo, depois coloca-se o agente para operar o processo redesenhado."),
        p("A resposta a essa pergunta define o ponto de entrada correto. E o ponto de entrada define se a transição cria valor ou apenas acelera o que já não funcionava."),
        h("O que AI Last parece na prática"),
        p("Empresas que operam com a lógica AI Last têm um sinal claro e verificável: para cada agente em produção, conseguem nomear qual mudança de processo o tornou possível, e não apenas qual tarefa ele executa."),
        p("“Nosso agente de qualificação de leads processa 300 leads por dia” não é AI Last. É IA com processo antigo."),
        p("“Redesenhamos o processo de qualificação para que a entrada chegue padronizada, eliminamos a etapa de validação manual que existia por precaução e não por necessidade, e então colocamos o agente para operar o fluxo novo” é AI Last. O processo veio primeiro. O agente veio depois."),
        h("A implicação para líderes"),
        p("AI Last não significa adiar a IA. Significa não pular a etapa que determina se o investimento vai funcionar."),
        p("O custo de redesenhar um processo antes de automatizá-lo é visível e mensurável. O custo de não fazer isso também é mensurável, mas aparece depois: agentes que não entregam o esperado, times frustrados com tecnologia que não funciona e lideranças que chegam à conclusão errada de que IA não é para a sua empresa."),
        p("A decisão de começar pelo processo não é conservadora. É a mais eficiente. Organizações que redesenham processos antes de implementar agentes são três vezes mais propensas a atribuir impacto real da IA ao resultado do negócio."),
        q("A tecnologia certa no processo errado não funciona. A tecnologia certa no processo certo transforma."),
      ],
    },

    /* ====================== ARTIGO 5 ====================== */
    {
      id: "processos-pessoas-ferramentas",
      kind: "article",
      cat: one("Método"),
      date: DATE,
      read: 6,
      art: "art-1",
      pdf: true,
      pdfUrl: PAPER,
      title: one("Processos, Pessoas e Ferramentas na sequência certa"),
      dek: one("Nessa ordem. Sempre. Não porque é a mais confortável — porque é a única que funciona."),
      body: [
        p("A maioria das empresas começa pela ferramenta. É compreensível. Ferramentas são concretas, têm preço, têm demo, têm contrato. Processos e pessoas são abstratos, demoram mais, exigem mais atenção de gestão."),
        p("O resultado é previsível. Seis meses de implementação, três reuniões de alinhamento por semana e um relatório de adoção que não reflete nenhuma mudança real nos resultados. A ferramenta ficou. A transformação não."),
        p("Isso não é falha da ferramenta. É falha de sequência."),
        h("Por que processos vêm primeiro"),
        p("Um agente de IA executa o que o processo manda. Se o processo está bem desenhado, o agente entrega bem. Se o processo tem etapas desnecessárias, aprovações redundantes e fluxos que existem por inércia, o agente vai executar tudo isso com consistência e velocidade."),
        q("Um agente executando um processo ruim é apenas caos mais rápido."),
        p("Mapear processos antes de implementar qualquer agente não é burocracia. É a única forma de garantir que o agente vai operar sobre algo que vale a pena operar. O diagnóstico correto responde a três perguntas: onde a empresa perde tempo, dinheiro e qualidade? Quais processos são mais repetitivos? Onde o erro humano tem maior custo?"),
        p("As respostas definem onde a IA vai ter maior impacto. Sem esse mapeamento, a empresa não está implementando IA estrategicamente. Está experimentando com custo real e sem métrica de sucesso definida."),
        h("Por que pessoas vêm em segundo"),
        p("Empresas que implementam agentes sem preparar o time chegam ao mesmo resultado: a ferramenta vira mais um software subutilizado. Não é resistência à mudança. É falta de preparo. E a responsabilidade é da liderança, não do time."),
        p("Preparar pessoas para trabalhar com agentes exige três coisas: comunicação honesta sobre o que vai mudar e por que; treinamento prático sobre como o trabalho vai funcionar com os agentes em operação; e clareza sobre o que se espera de cada pessoa no novo modelo."),
        p("Quando as pessoas entendem que o objetivo não é substituí-las, mas liberá-las do trabalho operacional para que foquem no que só humanos fazem, a resistência desaparece. O que fica é energia para construir."),
        p("95% dos profissionais em empresas que fizeram a transição agêntica corretamente reportam impacto positivo na satisfação com o trabalho. (MIT/BCG) O número não surpreende. Ninguém fica satisfeito fazendo trabalho repetitivo que uma máquina poderia fazer melhor."),
        h("Por que ferramentas vêm por último"),
        p("Ferramentas de IA são a última ponta, não a primeira. Só fazem sentido quando as duas anteriores estão no lugar."),
        p("Isso não significa que a empresa vai esperar meses para contratar qualquer ferramenta. Significa que a escolha da ferramenta é consequência do processo redesenhado e das pessoas preparadas, não o ponto de partida."),
        p("Uma empresa que mapeou seus processos e sabe exatamente o que precisa automatizar vai contratar a ferramenta certa para aquele processo específico. Uma empresa que começa pela ferramenta vai comprar o que parece mais promissor, adaptar os processos à lógica da ferramenta e descobrir, meses depois, que a ferramenta resolve bem um problema que não era o mais importante."),
        h("O que acontece quando a ordem é invertida"),
        p("Os três padrões de fracasso que acompanhamos com mais frequência têm origem direta na inversão dessa sequência."),
        p("O primeiro é implementar IA em processos desorganizados. O resultado é escalar o problema. A IA produz mais volume na mesma direção errada."),
        p("O segundo é implementar IA sem preparar as pessoas. O resultado é abandono. O time não usa a ferramenta, ou usa de forma que não gera valor, e a liderança conclui que “IA não funcionou”."),
        p("O terceiro é começar pela ferramenta mais interessante, não pelo processo mais impactante. O resultado é um caso de uso de baixo impacto que não financia a próxima etapa da transformação."),
        h("A sequência que funciona"),
        p("Processos, pessoas, ferramentas. Nessa ordem. Sempre. Não porque é a sequência mais confortável. Porque é a única que garante que o agente vai operar sobre algo que vale a pena, com um time que sabe o que fazer com o resultado."),
        p("A boa notícia é que essa sequência não precisa ser longa. Empresas que começam com um processo de alto impacto, mapeiam em profundidade, preparam o time responsável por ele e constroem o agente para aquele processo específico conseguem resultado mensurável em 30 a 90 dias. E esse resultado financia tudo que vem depois."),
      ],
    },

    /* ====================== ARTIGO 6 ====================== */
    {
      id: "4-niveis-maturidade-agentica",
      kind: "article",
      cat: one("Maturidade"),
      date: DATE,
      read: 7,
      art: "art-2",
      pdf: true,
      pdfUrl: PAPER,
      title: one("Os 4 níveis de maturidade agêntica e em qual estágio sua empresa está"),
      dek: one("Quatro estágios com características concretas. Saber onde você está é a condição para o próximo passo."),
      body: [
        p("Não existe transformação agêntica instantânea. Empresas que tentam passar do modelo industrial para a operação agêntica em um único movimento fracassam. O caminho é progressivo, com estágios distintos e características operacionais concretas em cada um."),
        p("Saber onde sua empresa está não é exercício acadêmico. É a condição para saber qual é o próximo passo correto."),
        h("Nível 1: Copiloto Individual"),
        p("No primeiro nível, os funcionários usam IA como assistente pessoal. ChatGPT, Copilot, Claude. O uso é individual, sem integração com processos da empresa e sem política de governança."),
        p("Isso tem valor real: profissionais reportam ganhos de 20% a 30% na produtividade individual. Mas não muda a empresa. Cada pessoa usa de um jeito, com suas próprias ferramentas, sem padronização e sem aprendizado institucional. O resultado permanece invisível para a organização como um todo."),
        p("O risco nesse nível não é a falta de produtividade. É a ilusão de que “já estamos usando IA” quando a empresa está no estágio mais primitivo da adoção. Essa ilusão impede a decisão de realmente investir. 65% das empresas globais opera no Nível 1 hoje."),
        h("Nível 2: Automação de Tarefas"),
        p("No segundo nível, a empresa seleciona processos específicos e implementa agentes para automatizá-los. IA está integrada a processos, com supervisão humana significativa. Existe um responsável pela iniciativa. Existem métricas básicas."),
        p("O impacto típico é de 20% a 40% de redução de custo nos processos automatizados. É resultado real, mas ainda limitado ao escopo de cada agente."),
        p("O risco principal nesse nível é a proliferação de plataformas: cada área compra sua própria ferramenta de IA, nenhuma conversa com a outra, a empresa acumula custos sem ganhar escala. 63% dos executivos identificam esse problema em suas organizações. (Bain)"),
        h("Nível 3: Workflows Agênticos Funcionais"),
        p("No terceiro nível, a empresa redesenha processos inteiros para serem agent-first dentro de uma função. Não é IA inserida no processo antigo. É o processo reconstruído com agentes no centro."),
        p("Aqui a empresa deixa de “usar IA” e começa a ser agêntica numa função específica. Novos papéis emergem. Governança formal é estabelecida. Agentes tomam decisões operacionais dentro de parâmetros definidos. KPIs incluem métricas de agentes."),
        p("O impacto típico é de 60% a 80% de automação nos processos-alvo. A diferença em relação ao Nível 2 é estrutural, não incremental. 9% das empresas opera no Nível 3 hoje."),
        h("Nível 4: Sistemas Agênticos Cross-Funcionais"),
        p("No quarto nível, agentes operam entre funções com capacidade de decisão coordenada. O agente de vendas se comunica com o de operações. O agente financeiro valida margem antes da proposta sair. A organização funciona como rede integrada, não como silos com automação isolada."),
        p("Humanos definem estratégia e supervisionam. Agentes executam. O papel de gestor de agentes é formal, com faixa salarial e autoridade definidas. A cultura agêntica está consolidada."),
        p("O impacto típico é de 70% a 80% de redução de custo por transação. (McKinsey) Menos de 1% das organizações globais opera no Nível 4 hoje. Quem chegar primeiro terá vantagem competitiva que será progressivamente mais difícil de alcançar."),
        h("Onde sua empresa está"),
        p("Cinco perguntas indicam o nível com precisão. Quantos agentes de IA estão em produção hoje, com responsável formal pelo seu funcionamento? Existe alguém cujo trabalho principal é garantir que os agentes entregam o resultado esperado, não apenas configurá-los? Algum processo core foi redesenhado tendo agentes como parte do fluxo, não como complemento? A estrutura de recompensa da organização distingue de alguma forma quem orquestra sistemas de quem executa tarefas? A liderança consegue nomear os três processos onde agentes geram maior impacto nos próximos 12 meses?"),
        p("Uma ou duas respostas afirmativas indicam Nível 2. Três ou quatro indicam Nível 3. Cinco indicam que a empresa está próxima do Nível 4, ou subestimando o que ainda falta para chegar lá."),
        h("O próximo passo"),
        q("Empresas não pulam do Nível 1 para o Nível 4. As que tentam fracassam."),
        p("O caminho é progressivo: provar valor antes de escalar. A transição do Nível 1 para o Nível 2 leva até 30 dias quando bem executada. Do Nível 2 para o Nível 3, de 30 a 90 dias. Do Nível 3 para o Nível 4, de três a seis meses."),
        p("A variável que mais impacta a velocidade não é o orçamento. É a clareza sobre onde a empresa está e a disciplina para seguir a sequência correta."),
      ],
    },

    /* ====================== ARTIGO 7 ====================== */
    {
      id: "organograma-agentico",
      kind: "article",
      cat: one("Estrutura"),
      date: DATE,
      read: 7,
      art: "art-3",
      pdf: true,
      pdfUrl: PAPER,
      title: one("O Organograma Agêntico e como fica o time com agentes"),
      dek: one("O organograma tradicional descreve quem manda em quem. A organização agêntica precisa de outro mapa."),
      body: [
        p("O organograma que a maioria das empresas usa hoje descreve quem reporta a quem. Esse mapa foi útil enquanto o trabalho era executado exclusivamente por humanos. Numa organização agêntica, ele não descreve mais onde o trabalho acontece."),
        p("O trabalho em uma organização agêntica acontece na interface entre humanos e agentes. E essa interface exige um mapa diferente."),
        h("O problema com o organograma tradicional"),
        p("Organogramas hierárquicos foram desenhados para responder a uma pergunta: quem manda em quem? Essa pergunta faz sentido quando o trabalho flui de cima para baixo, quando decisões precisam ser escaladas para quem tem mais contexto e quando coordenação depende de autoridade formal."),
        p("Numa organização agêntica, o trabalho não flui assim. Agentes executam tarefas em tempo real, em paralelo, conectados a sistemas e a outros agentes. A pergunta relevante não é mais “quem manda em quem?”. É “quem é responsável por qual entrega?”."),
        p("A McKinsey usa o conceito de work chart para descrever esse mapa: uma estrutura que mostra quem é responsável por qual resultado, independentemente de posição hierárquica. O work chart coexiste com o organograma, mas é ele que descreve onde o valor é criado."),
        h("A arquitetura em quatro camadas"),
        p("Toda organização agêntica funcional tem quatro camadas que precisam estar claras antes de qualquer implementação."),
        p("A primeira é a camada humana. É onde vivem a supervisão e a decisão estratégica. Humanos definem objetivos, aprovam mudanças de escopo, resolvem exceções que saíram dos parâmetros e são responsáveis pelos resultados que os agentes geram. Essa camada está sempre no topo. Não porque seja mais ativa no dia a dia, mas porque é onde a responsabilidade final reside."),
        p("A segunda é a camada de interação. É onde acontecem os briefings, as aprovações e os reviews entre humanos e agentes. Não toda saída de agente vai para revisão humana. Mas toda saída de alto impacto, toda decisão fora do padrão e toda situação nova passa por essa camada antes de seguir adiante."),
        p("A terceira é a camada de agentes. É onde acontece a execução operacional. Agentes processam, decidem dentro de seus parâmetros e executam de ponta a ponta. É a camada mais ativa no dia a dia, mas opera sempre dentro dos limites definidos pelas camadas acima."),
        p("A quarta é a camada de sistemas. São os CRMs, ERPs, bases de dados e APIs com os quais os agentes se conectam para operar. Sem essa integração, agentes não são membros da equipe. São ferramentas isoladas."),
        h("O papel que define o novo modelo"),
        p("O papel mais importante que emerge numa organização agêntica não existe na maioria dos organogramas hoje. Tem diferentes nomes dependendo da empresa: gestor de agentes, orquestrador, agent manager. O conceito é o mesmo."),
        p("O agent manager é o profissional responsável por garantir que os agentes entregam o resultado esperado. Não por configurá-los tecnicamente. Por governar o que fazem: avaliar se estão performando, identificar quando o escopo precisa de ajuste, escalar situações que o agente não consegue resolver e garantir que o trabalho do agente está alinhado com o objetivo do negócio."),
        p("O que distingue um bom agent manager não é conhecimento técnico de IA. É domínio profundo do processo que o agente opera, do cliente que ele atende e do resultado que deveria entregar. Os melhores agent managers vêm de operações, delivery e customer success. Já eram os profissionais que mais entendiam o processo. Agora são os responsáveis por fazer o sistema que executa esse processo funcionar bem."),
        p("O HBR identificou formalmente esse papel em 2026: profissional responsável por orquestrar como agentes de IA aprendem, colaboram, performam e operam com segurança ao lado de humanos. O background mais relevante para esse papel, segundo o HBR, não é técnico. É operacional."),
        p("Esse papel já existe em muitas organizações, sem nome formal, sem faixa salarial correspondente e sem autoridade reconhecida. Formalizá-lo antes da pressão da transformação é uma das decisões mais estratégicas que uma empresa pode tomar agora."),
        h("O que não muda"),
        p("A mudança na estrutura não altera um princípio fundamental: humanos sempre no centro da decisão. Agentes executam. Humanos supervisionam, definem os limites e tomam as decisões que têm consequências além do operacional. A autonomia de um agente nunca é absoluta. É sempre delegada, definida e revogável."),
        p("Uma organização que delega decisões estratégicas a agentes não é uma organização agêntica avançada. É uma organização sem governança."),
        h("O sinal de que a estrutura está funcionando"),
        p("Há um sinal claro de que a arquitetura agêntica está funcionando como deveria: líderes conseguem nomear, para cada agente em produção, qual humano é responsável por aquele agente e qual resultado esse agente deveria entregar. Quando a resposta a essa pergunta é vaga, a estrutura não está funcionando. O agente pode estar rodando, mas não está sendo governado."),
        q("Agente sem governança não é capacidade organizacional. É risco operacional."),
      ],
    },

    /* ====================== ARTIGO 8 ====================== */
    {
      id: "agentes-vs-automacao-tradicional",
      kind: "article",
      cat: one("Conceito"),
      date: DATE,
      read: 6,
      art: "art-4",
      pdf: true,
      pdfUrl: PAPER,
      title: one("Agentes de IA vs. automação tradicional"),
      dek: one("Regras fixas ou interpretação de contexto: qual usar — e por que a escolha define o roadmap."),
      body: [
        p("63% dos executivos identificam a proliferação de ferramentas como um dos principais obstáculos à transformação com IA. (Bain) Parte desse problema vem de uma confusão que parece técnica, mas tem consequências estratégicas: a diferença entre automação tradicional e agentes de IA."),
        p("A confusão não é sem motivo. Os dois modelos executam tarefas que antes eram feitas por humanos. Os dois reduzem o trabalho manual. Os dois aparecem nas mesmas apresentações de transformação. Mas funcionam de formas fundamentalmente diferentes, e aplicar um quando o outro era necessário é um dos erros mais custosos que uma empresa pode cometer nesse momento."),
        h("Como a automação tradicional funciona"),
        p("Automação tradicional, como RPA (Robotic Process Automation) e scripts de processo, opera com base em regras fixas. O sistema executa uma sequência predefinida de ações, nas condições previstas, sem capacidade de interpretar variações."),
        p("É eficiente onde as condições são controladas. Um processo que sempre recebe dados no mesmo formato, com os mesmos campos, em sequência previsível, funciona bem com automação tradicional. O sistema não comete erros de atenção, não se distrai, não esquece etapas."),
        p("O limite é a rigidez. Quando a condição esperada não se verifica, a automação para ou comete um erro que nenhum humano cometeria. O dado veio com um campo extra. O sistema não reconheceu o formato. O processo travou. Alguém precisou intervir manualmente."),
        p("Em ambientes de baixa variação, automação tradicional é uma escolha correta e de menor custo de implementação. O erro é usá-la em ambientes que exigem interpretação de contexto."),
        h("Como agentes de IA funcionam"),
        p("Agentes de IA operam de forma estruturalmente diferente em três dimensões."),
        p("A primeira é a interpretação de contexto. Agentes não seguem regras fixas. Processam informação variável, entendem o objetivo da tarefa e decidem como executá-la de acordo com a situação específica. O dado veio com formato diferente. O agente lê o conteúdo, identifica as informações relevantes e age de acordo com o objetivo, não com a regra."),
        p("A segunda é a tomada de decisão dentro de parâmetros. Dentro do escopo definido, o agente decide o que fazer sem intervenção humana em cada etapa. Ele não executa uma sequência predefinida. Ele executa o objetivo, escolhendo a sequência mais adequada para a situação que encontrou."),
        p("A terceira é a integração dinâmica. Agentes se conectam a sistemas, APIs e outras ferramentas em tempo real, buscando as informações necessárias para completar a tarefa. Não operam com dados estáticos. Operam com o estado atual dos sistemas da empresa."),
        h("Quando usar cada um"),
        q("A escolha entre automação tradicional e agente de IA não é uma questão de qual é melhor. É uma questão de qual é adequado para o processo em questão."),
        p("Automação tradicional é a escolha certa quando o processo tem entrada padronizada e previsível, quando as regras são fixas e conhecidas, quando não há necessidade de interpretar contexto e quando o volume é alto e a variação é baixa. Extração de dados de formulários padronizados, transferência de dados entre sistemas com estrutura definida e execução de aprovações em fluxos sem exceção são candidatos naturais."),
        p("Agentes de IA são a escolha certa quando o processo envolve variação, quando a tomada de decisão exige interpretação de contexto, quando as exceções são frequentes o suficiente para tornar a automação tradicional frágil e quando o objetivo é que o sistema opere com inteligência real sobre o que processa. Qualificação de leads, triagem de atendimento, análise de contratos e coordenação entre sistemas são candidatos naturais."),
        h("Por que a distinção define o roadmap"),
        p("Empresas que tratam automação tradicional e agentes de IA como equivalentes fazem dois tipos de erro opostos."),
        p("O primeiro é usar automação tradicional onde um agente era necessário. O resultado é um sistema que funciona nas condições previstas e quebra nas exceções, forçando intervenção humana constante e destruindo a eficiência que deveria ter sido criada."),
        p("O segundo é usar agentes onde automação tradicional seria suficiente. O resultado é custo de implementação e governança maior do que o processo justifica, e uma percepção de que “a IA foi cara demais para o que entregou”."),
        p("O diagnóstico correto começa pela natureza do processo: alta variação ou baixa variação, contexto fixo ou contexto dinâmico, regras conhecidas ou julgamento necessário. Essa análise define qual arquitetura faz sentido antes de qualquer decisão de ferramenta."),
        p("Uma estratégia de IA que combina automação tradicional e agentes no lugar certo de cada um não é mais sofisticada. É mais eficiente. E eficiência é o que distingue transformação agêntica de investimento sem retorno."),
      ],
    },

    /* ====================== ARTIGO 9 ====================== */
    {
      id: "ia-agentica-vs-generativa",
      kind: "article",
      cat: one("Conceito"),
      date: DATE,
      read: 6,
      art: "art-1",
      pdf: true,
      pdfUrl: PAPER,
      title: one("IA agêntica vs. IA generativa: qual implementar primeiro"),
      dek: one("Tecnologias relacionadas, impactos organizacionais opostos. A ordem é uma questão de dependência."),
      body: [
        p("Toda semana, alguma empresa anuncia que está “implementando IA”. O que a maioria das vezes está implementando é IA generativa: ferramentas que geram texto, resumem documentos, respondem perguntas e assistem profissionais em tarefas cognitivas."),
        p("IA generativa e IA agêntica são tecnologias relacionadas, mas com impactos organizacionais fundamentalmente diferentes. Confundi-las leva empresas a acreditar que estão mais avançadas na transformação do que estão, e a tomar decisões de investimento baseadas nessa percepção equivocada."),
        h("O que é IA generativa"),
        p("IA generativa é a categoria de sistemas que gera conteúdo, textos, imagens, código ou análises, com base em um input humano. ChatGPT, Claude, Gemini, Copilot. O modelo processa o que o humano pede e entrega uma resposta."),
        p("O humano decide o que pedir. O humano avalia a resposta. O humano decide o que fazer com ela. IA generativa amplifica a capacidade do profissional individual de processar informação e produzir output. Não age por conta própria. Não executa processos. Não se integra a sistemas da empresa sem que alguém configure essa integração."),
        p("É uma ferramenta poderosa de produtividade individual. Não é uma mudança de modelo operacional."),
        h("O que é IA agêntica"),
        p("IA agêntica é a categoria de sistemas que age de forma autônoma dentro de parâmetros definidos. Não apenas gera uma resposta. Executa um processo de ponta a ponta: busca informação nos sistemas, toma decisões dentro do seu escopo, aciona outras ferramentas, registra o resultado e escala para o humano apenas quando a situação sai dos parâmetros."),
        p("A IA agêntica não amplifica o profissional individual. Redistribui o trabalho operacional da equipe para o sistema agêntico, liberando humanos para o trabalho que exige julgamento, criatividade e relacionamento."),
        q("IA generativa muda o que uma pessoa produz. IA agêntica muda como a empresa opera."),
        h("Por que IA generativa não transforma organizações"),
        p("Uma empresa onde todos os profissionais usam IA generativa todos os dias é uma empresa com profissionais mais produtivos individualmente. Os e-mails ficam prontos mais rápido. As análises ficam mais elaboradas. As apresentações melhoram."),
        p("Mas o processo de aprovação ainda leva 48 horas. A informação ainda fica presa em silos. O melhor vendedor ainda passa duas horas por dia atualizando o CRM. A estrutura de custos permanece a mesma."),
        p("A IA generativa otimiza o trabalho humano dentro de um modelo operacional que não mudou. IA agêntica muda o modelo operacional."),
        p("Isso não significa que IA generativa não tem valor. Tem, e significativo. Significa que empresas que param na IA generativa acreditando que fizeram a transformação agêntica vão se surpreender quando concorrentes no modelo agêntico passarem a operar com estrutura de custos 70% menor por transação."),
        h("A sequência que faz sentido"),
        p("A ordem não é uma questão de preferência. É uma questão de dependência."),
        p("IA agêntica pressupõe que a empresa tem processos mapeados, pessoas preparadas para trabalhar com agentes e governança estabelecida. Empresas que ainda estão no uso individual e assistemático de IA generativa ainda não têm essa base."),
        p("A sequência natural começa com IA generativa como ferramenta de aprendizado organizacional. As empresas entendem como a IA funciona, que limitações tem, como os profissionais reagem a ela e onde cria mais valor. Esse aprendizado informa as decisões sobre quais processos são candidatos à transformação agêntica."),
        p("Depois, com processos mapeados e time preparado, a IA agêntica entra para transformar como o trabalho é feito, não apenas como ele é assistido."),
        p("Tentar implementar IA agêntica sem essa base é colocar um agente num processo que ninguém entende bem o suficiente para definir seus parâmetros. O resultado é um agente com escopo mal definido operando num processo mal desenhado. O fracasso não é da tecnologia."),
        h("A pergunta que define o momento certo"),
        p("A transição de IA generativa para IA agêntica está pronta quando a empresa consegue responder com convicção a uma única pergunta: qual processo, se operado por agentes, liberaria nosso time para o trabalho que só humanos fazem e geraria resultado mensurável nos próximos 90 dias?"),
        p("Quando a resposta é vaga ou ausente, a empresa ainda não tem a clareza de processo que a transformação agêntica exige. Investir em diagnóstico, em mapeamento e em preparação de pessoas antes de avançar para a implementação agêntica é mais eficiente do que acelerar antes da hora."),
        p("Quando a resposta é precisa, a empresa está pronta. E a janela para criar vantagem competitiva real com IA agêntica está aberta agora."),
      ],
    },
  ];

  window.DL_ARTICLES = (window.DL_ARTICLES || []).concat(NEW);
})();
