/* Dados da página de casos — compartilhado entre casos-desktop.html e casos-mobile.html */
window.CASOS = {
  dados: [
    {"setor":"Financeiro","estagio":"POC","papel":"Analista de Conciliação Financeira","cliente":"Agência global de marketing","headline":"O que escapava na planilha virou alerta no mesmo dia.","comparativo":null,"kpis":[{"numero":"~R$26mil","rotulo":"em divergências achadas no primeiro ciclo"},{"numero":"3","rotulo":"fontes cruzadas todo dia"}],"problema":"Pagamentos duplicados e notas divergentes entre 3 fontes (ERP, planilha interna e notas fiscais); só no primeiro ciclo, o agente achou cerca de R$26 mil fora de controle.","comoTrabalhava":"Conciliação manual, e a divergência só aparecia quando já tinha virado problema.","oQueMudou":"O agente cruza as três fontes todo dia, e o financeiro decide sobre o alerta em vez de procurar o erro.","fluxo":["Cruza notas, ERP e planilha","Detecta divergências","Bloqueia alteração indevida","Alerta e consolida","Humano decide sobre o alerta"],"fluxoVivo":true},
    {"setor":"Jurídico","estagio":"Ativo e operante","papel":"Analista de Conformidade Regulatória","cliente":"Instituição financeira regulada pelo Bacen","headline":"A matriz regulatória do Bacen deixou de depender de conferência manual.","comparativo":null,"kpis":[{"numero":"378","rotulo":"processos monitorados no Bacen"},{"numero":"0","rotulo":"atualização do Bacen perdida"}],"problema":"378 processos no Bacen para acompanhar, com normas e atualizações espalhadas, exigindo conferência manual para manter a matriz regulatória organizada e em dia.","comoTrabalhava":"Advogados conferindo norma por norma e atualizando a matriz à mão, com risco de passar atualização batido.","oQueMudou":"O agente confere os 378 processos e organiza a matriz regulatória do Bacen, e o advogado valida o que muda.","fluxo":["Lê as publicações do Bacen","Confere contra a matriz","Organiza e classifica","Sinaliza o que mudou","Advogado valida a mudança"],"fluxoVivo":false},
    {"setor":"Jurídico","estagio":"Ativo e operante","papel":"Analista de Contencioso","cliente":"Operação de contencioso jurídico","headline":"O contencioso inteiro passou a se manter organizado sozinho.","comparativo":null,"kpis":[{"numero":"+50","rotulo":"PDFs de +30 páginas organizados"},{"numero":"~1.500","rotulo":"páginas lidas e classificadas"},{"numero":"0","rotulo":"prazo de contencioso perdido"}],"problema":"Mais de 50 e-mails com PDFs de mais de 30 páginas cada, cerca de 1.500 páginas, exigindo leitura e organização manual de prazos, andamentos e documentos.","comoTrabalhava":"Cada PDF aberto e classificado à mão, com prazo dependendo de alguém lembrar.","oQueMudou":"O agente lê os +50 PDFs, organiza o contencioso e mantém prazos e andamentos em ordem, e o advogado atua na estratégia.","fluxo":["Recebe o e-mail e o PDF","Lê e classifica o processo","Organiza prazos e documentos","Alerta o prazo","Advogado decide a estratégia"],"fluxoVivo":false},
    {"setor":"Jurídico","estagio":"Ativo e operante","papel":"Analista de Reporte e Reuniões","cliente":"Departamento jurídico corporativo","headline":"A coordenação de 120 pessoas e a rotina de reuniões deixaram de pesar no advogado.","comparativo":null,"kpis":[{"numero":"120","rotulo":"pessoas coordenadas"},{"numero":"+13/sem","rotulo":"reuniões com reporte e briefing"}],"problema":"Coordenação de 120 pessoas que realizam mais de 13 reuniões por semana, com reporte de movimentação e agenda consumindo tempo dos advogados.","comoTrabalhava":"Cada movimentação virava e-mail manual, e o pré e pós das +13 reuniões semanais ficava sem apoio.","oQueMudou":"O agente coordena as 120 pessoas, cuida do reporte e do briefing das reuniões, e o advogado foca na tese.","fluxo":["Monitora a movimentação","Resume e classifica","Prepara o reporte","Briefing pré e pós-reunião","Advogado conduz o caso"],"fluxoVivo":false},
    {"setor":"Previdência","estagio":"Ativo e operante","papel":"Analista de Cobrança e Recuperação","cliente":"Operadora de previdência privada","headline":"A cobrança e a recuperação de crédito viraram um agente em operação.","comparativo":null,"kpis":[{"numero":"+300mil","rotulo":"CPFs na base de cobrança"},{"numero":"51mil","rotulo":"contratos ativos na carteira"},{"numero":"R$6M/mês","rotulo":"de faturamento"}],"problema":"Base de mais de 300 mil CPFs em cobrança sobre uma carteira de 51 mil contratos ativos e R$6M por mês, tudo trabalhado manualmente, contrato a contrato.","comoTrabalhava":"Equipe correndo atrás da inadimplência em 51 mil contratos, sem escala para os 300 mil CPFs da régua.","oQueMudou":"O agente aborda, negocia e concilia em operação 24/7, e o humano fica só com o caso sensível.","fluxo":["Recebe a base inadimplente","Aborda e negocia prazos","Gera os documentos","Registra e concilia","Humano cuida do caso sensível"],"fluxoVivo":true},
    {"setor":"Saúde","estagio":"Em andamento","papel":"Pré-vendas e Atendimento ao Cliente","cliente":"Multinacional de dispositivos médicos","headline":"A operação brasileira virou referência de IA dentro do grupo global.","comparativo":{"label":"Antes → Com o agente","pares":[{"rotulo":"Chatbots fragmentados, antes","valor":"3"},{"rotulo":"Agentes mirando o lançamento","valor":"49"}],"nota":"5x de ROI no contrato âncora · SDR e SAC unificados"},"kpis":[{"numero":"49","rotulo":"agentes mirando o lançamento"},{"numero":"5x","rotulo":"de ROI no contrato âncora"}],"problema":"Back office e front office pedindo escala, com a operação brasileira liderando a inovação no grupo.","comoTrabalhava":"Marketing e atendimento fragmentados, três chatbots, leads parados na transição comercial.","oQueMudou":"49 agentes mirando o lançamento, com SDR e SAC unificados e o marketing como case piloto que cascateia para as outras diretorias.","fluxo":["Recebe o lead ou o chamado","Qualifica e prioriza","Direciona a execução","Integra HubSpot e Monday","Humano fecha e decide"],"fluxoVivo":true},
    {"setor":"Varejo","estagio":"Vitrine","papel":"Analista de Comunicação Interna","cliente":"Rede de varejo alimentar","headline":"A comunicação de uma rede com +2.000 funcionários virou um agente, e a base de vendas virou conversa.","comparativo":null,"kpis":[{"numero":"+2.000","rotulo":"funcionários na comunicação interna"},{"numero":"2","rotulo":"fontes (o ERP da rede e o BI) em linguagem natural"}],"problema":"Uma rede com mais de 2.000 funcionários e 2 sistemas (o ERP da rede e o BI) guardando os dados de venda, que só viravam comunicação e decisão com colaboradores humanos técnicos no meio.","comoTrabalhava":"Relatórios e comunicação interna montados manualmente.","oQueMudou":"Um agente de comunicação conversa com a base e leva a informação certa aos +2.000 funcionários.","fluxo":["Lê a base (ERP e BI)","Entende a pergunta","Responde em linguagem natural","Comunica aos times","Humano publica"],"fluxoVivo":false},
    {"setor":"Serviços","estagio":"Ativo e operante","papel":"Atendente de Agendamento","cliente":"Instituição com milhares de membros","headline":"O agendamento de milhares de membros virou conversa por WhatsApp.","comparativo":null,"kpis":[{"numero":"+2.000/mês","rotulo":"pessoas atendidas no agendamento"}],"problema":"Mais de 2.000 pessoas por mês pedindo agendamento sem um canal único, dependendo de pessoas para consultar agenda, confirmar e lembrar.","comoTrabalhava":"Agendamento manual, consulta de disponibilidade e confirmação no esforço, pessoa a pessoa.","oQueMudou":"Um agente no WhatsApp recebe, consulta a agenda, confirma e lembra automaticamente, para +2.000 pessoas por mês.","fluxo":["Recebe a solicitação","Consulta a agenda","Oferece horários","Confirma e lembra","Humano cuida da exceção"],"fluxoVivo":false},
    {"setor":"Saúde","estagio":"Ativo e operante","papel":"Assistente de Acompanhamento","cliente":"Operação de saúde e performance","headline":"Mais de 200 pessoas por dia acompanhadas, com o profissional na decisão.","comparativo":null,"kpis":[{"numero":"+200/dia","rotulo":"pessoas atendidas em São Paulo"}],"problema":"Mais de 200 pessoas por dia, em São Paulo, para orientar e acompanhar, muito além do que cabe numa agenda de atendimento individual.","comoTrabalhava":"Acompanhamento limitado à agenda e ao profissional disponível, uma pessoa de cada vez.","oQueMudou":"Um agente orienta e acompanha +200 pessoas por dia em paralelo, e o profissional decide o cuidado.","fluxo":["Recebe a demanda","Orienta e organiza a rotina","Acompanha a evolução","Sinaliza quando precisa","Profissional decide o cuidado"],"fluxoVivo":false},
    {"setor":"Financeiro","estagio":"Ativo e operante","papel":"Analista de Pré-vendas","cliente":"Operação do setor financeiro","headline":"A qualificação de leads virou +R$50 mil por mês que antes esfriava na fila.","comparativo":null,"kpis":[{"numero":"~18%","rotulo":"recuperados que esfriavam na fila"},{"numero":"24/7","rotulo":"qualificação e follow-up sem parar"}],"problema":"Leads chegando em volume e esfriando na fila, dependendo de alguém para qualificar e dar follow-up, mais de R$50 mil por mês escapando.","comoTrabalhava":"Qualificação e follow-up manuais, com o lead bom esfriando antes do contato.","oQueMudou":"O agente qualifica e faz o follow-up na hora, recupera +R$50 mil por mês, e o time comercial fala só com quem está pronto.","fluxo":["Recebe o lead","Qualifica o perfil","Faz o follow-up","Agenda o que está quente","Humano conduz a venda"],"fluxoVivo":false}
  ],
  vitrines: [["R$26 mil","em divergências flagradas no primeiro ciclo"],["zero","atualizações do Bacen perdidas"],["~1.500","páginas de contencioso organizadas"],["120","pessoas coordenadas por um agente"],["+300 mil","CPFs em cobrança ativa"],["5x","de ROI no contrato âncora"],["+2.000","funcionários atendidos por um agente"],["+2.000/mês","agendamentos resolvidos no WhatsApp"],["+200/dia","pessoas acompanhadas em paralelo"],["+R$50 mil","recuperados por mês da fila de leads"]],
  perguntas: [
    ["Como achar a divergência ","antes"," que ela vire prejuízo?"],
    ["Como não perder ","nenhuma"," atualização do Bacen?"],
    ["Como manter mil e quinhentas páginas ","em ordem","?"],
    ["Como coordenar cento e vinte pessoas sem ","pesar"," no advogado?"],
    ["Como cobrar trezentos mil CPFs ","um a um","?"],
    ["Como unificar pré-vendas e atendimento em ","escala global","?"],
    ["Como fazer a base de vendas ","conversar"," com dois mil funcionários?"],
    ["Como agendar dois mil pessoas por mês ","sem fila","?"],
    ["Como acompanhar duzentas pessoas por dia ","em paralelo","?"],
    ["Como parar de perder cinquenta mil reais por mês na ","fila","?"]
  ],
  setores: ["Todos","Financeiro","Jurídico","Saúde","Varejo","Previdência","Serviços"],
  cores: {"Financeiro":"#a8d8ff","Previdência":"#a8d8ff","Jurídico":"#c9b8ff","Logística":"#a8f0cf","Serviços":"#a8f0cf","Saúde":"#ffb8d9","Varejo":"#ffd7a8","Tecnologia":"#dfe7f2","Educação":"#dfe7f2","Corporativo":"#dfe7f2"},
  icones: {"Financeiro":"M8 2.6a5.4 5.4 0 1 0 0 10.8a5.4 5.4 0 1 0 0-10.8","Previdência":"M8 2.6a5.4 5.4 0 1 0 0 10.8a5.4 5.4 0 1 0 0-10.8M8 5.6a2.4 2.4 0 1 0 0 4.8a2.4 2.4 0 1 0 0-4.8","Jurídico":"M3 3h10v10H3Z","Logística":"M8 1.9 14.1 8 8 14.1 1.9 8Z","Serviços":"M5.5 3l6 5-6 5","Saúde":"M8 2.4v11.2M2.4 8h11.2","Varejo":"M8 1.8l5.4 3.1v6.2L8 14.2l-5.4-3.1V4.9Z","Tecnologia":"M3 3h10v10H3ZM8 3v10","Educação":"M8 2.6 14 13.4H2Z","Corporativo":"M3 5.4h10M3 10.6h10"},
  publico: function(e){ return e === "Ativo e operante" ? "Em operação" : (e === "POC" || e === "Vitrine") ? "Prova de conceito" : "Em implantação"; }
};
